version: '2'
services:
  searchtelegram:
    image: knarfeh/searchtelegram
    build:
      context: .
      dockerfile: ./.docker/.dev.dockerfile
    ports:
      - "5000:5000"
      - "80:80"
    environment:
      ES_HOST_PORT: 'TODO'
    networks:
      - searchtelegram


networks:
  searchtelegram:
    driver: bridge
