version: '2'
services:
  searchtelegram:
    image: daocloud.io/knarfeh/searchtelegramprivate:latest
    build:
      context: .
      dockerfile: ./.docker/.prod.dockerfile
    ports:
      - "5000:5000"
      - "80:80"
      - "443:443"
    env_file:
      - envs/secret.env
    volumes:
      - /var/www/searchtelegram.com:/le-root
      - ./conf/nginx.conf:/etc/nginx/searchtelegram_nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      ESHOSTPORT: 'http://elasticsearch:9200'
      REDISHOST: 'redis'
      REDISPORT: '6379'
    networks:
      - searchtelegram
  elasticsearch:
    build:
      context: .
      dockerfile: ./conf/es-kibana/prod/elasticsearch/Dockerfile
    volumes:
      - ./conf/es-kibana/prod/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./container-data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
    networks:
      - searchtelegram
  kibana:
    build:
      context: .
      dockerfile: ./conf/es-kibana/prod/kibana/Dockerfile
    volumes:
      - ./conf/es-kibana/prod/kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - searchtelegram
  redis:
    image: "redis:alpine"
    volumes:
      - ./container-data/redis:/data
    ports:
      - "6379:6379"
    networks:
      - searchtelegram

networks:
  searchtelegram:
    driver: bridge
