version: '2'
services:
  searchtelegram:
    image: daocloud.io/knarfeh/searchtelegramdev:latest
    build:
      context: .
      dockerfile: ./.docker/.dev.dockerfile
    volumes:
      - ./conf/nginx.conf:/etc/nginx/searchtelegram_nginx.conf
      # - ./container-data/nginx/static/images:/media/images
      - ./server:/go/src/github.com/knarfeh/searchtelegram/server
      - ./client:/go/src/github.com/knarfeh/searchtelegram/client
      - ./vendor:/go/src/github.com/knarfeh/searchtelegram/vendor
    ports:
      - "15000:5000"
      - "18080:80"
    entrypoint: [bash]
    tty: true
    env_file:
      - envs/secret.env
    environment:
      ESHOSTPORT: 'http://elasticsearch:9200'
      REDISHOST: 'redis'
      REDISPORT: '6379'
    networks:
      - searchtelegram
  elasticsearch:
    build:
      context: .
      dockerfile: ./conf/es-kibana/dev/elasticsearch/Dockerfile
    volumes:
      - ./conf/es-kibana/dev/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./container-data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - searchtelegram
  kibana:
    build:
      context: .
      dockerfile: ./conf/es-kibana/dev/kibana/Dockerfile
    volumes:
      - ./conf/es-kibana/dev/kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - searchtelegram
  redis:
    image: "redis:alpine"
    volumes:
      - ./container-data/redis:/data
    ports:
      - "16379:6379"
    networks:
      - searchtelegram

networks:
  searchtelegram:
    driver: bridge
